AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  ScpPolicy:
    Type: "AWS::Organizations::Policy"
    Properties:
      Name: "scp_root_account"
      Content: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"*\",\"Resource\":\"*\",\"Effect\":\"Deny\",\"Condition\":{\"StringLike\":{\"aws:PrincipalArn\":[\"arn:aws:iam::*:root\"]}}}]}"
      Type: "SERVICE_CONTROL_POLICY"
      Description: "This SCP prevents restricts the root user in an AWS account from taking any action, either directly as a command or through the console. "
Parameters: {}
Metadata: {}
Conditions: {}
